version: '3.8'
services:
  mysqldb:
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - .db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: 'ec2-db'
      MYSQL_USER: 'ec2_api'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: '%'
  backend:
    depends_on:
      - mysqldb
    ports:
      - 3333:3333
    build:
      dockerfile: ./Dockerfile
    stdin_open: true
    volumes:
      - .:/app
    networks:
      - default
