name: "Push to CodeCommit"

on:
    push:
        branches:
            - main

jobs:
    push-to-CodeCommit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Push
              env:
                  CODECOMMIT_URL: ${{ secrets.CODECOMMIT_URL }}
              run: |
                  git config --global --add safe.directory /github/workspace
                  git config --global credential.helper '!aws codecommit credential-helper $@'
                  git config --global credential.UseHttpPath true
                  git remote add aws-codecommit "$CODECOMMIT_URL"
                  git push aws-codecommit main